### ISSUE TITLE
undefined: redis DialUsername

### ISSUE THREAD

**Issue by idealage** [casbin/redis-adapter#47]
hi:
  Error reported after upgrading from Golang to 1.22: github.com casbin redis adapter/ v3@v3.5.0 /Adapter. go: 210:55: undefined: redis DialUsername (exit status 1)

**Comment by hsluoyz** [comment]
@idealage why close?
